import 'package:co_rhema/constants.dart';
import 'package:flutter/material.dart';
import 'package:flutter_vector_icons/flutter_vector_icons.dart';

class Specialist{
  final String? speciality,title,image,address,review,location,cat;
  final int? price,id,reviews,years;
  final double? ratings;
  final Color? color;
  final IconData? icon;
  Specialist({this.title,this.reviews,this.cat,this.icon, this.location, this.address,this.years, this.review, this.ratings, this.image, this.color, this.id, this.speciality, this.price});
  static List<Specialist> physicians =[Specialist(
  id: 1,
  title: "Dr. Jane Cooper",
  price: 234,
  ratings: 4.8,
  speciality: "Dentist",
  address: 'Fifth Settlement Medical Center',
  years: 10,
  review: '4,956',
  cat: 'address',
  icon: MaterialIcons.people,
  reviews: 49,
  location: 'Cairo, Egypt',
  image: "assets/images/docs/f_doc_1.jpg",
  color: myBlueColor), Specialist(
  id: 2,
  title: "Dr. Robert Fox",
  price: 234,
  ratings: 4.8,
  address: '4,500+',
  years: 7,
  review: '4,956',
  reviews: 49,
  cat: 'Years Exp.',
  location: 'Cairo, Egypt',
  icon: MaterialCommunityIcons.card,
  speciality: 'Dentist',
  // speciality: 'Cardiology',
  image: "assets/images/docs/m_doc_1.jpg",
  color: myBlueColor), Specialist(
  id: 3,
  title: "Dr. Jacob Jones",
  price: 234,
  ratings: 4.7,
  address: 'Fifth Settlement Medical Center',
  years: 7,
  review: '4,695',
  cat: 'Rating',
  icon: MaterialIcons.star,
  speciality: 'Dentist',
  location: 'Cairo, Egypt',
  reviews: 46,
  image: "assets/images/docs/doc_x.jpg",
  color: myBlueColor), Specialist(
  id: 4,
  title: "Dr. Jacob Jones",
  price: 234,
  ratings: 11,
  address: '3,650+',
  years: 6,
  review: '4,643',
  reviews: 46,
  cat: 'Rating',
  icon: MaterialIcons.comment,
  location: 'Cairo, Egypt',
  speciality: 'Dentist',
  image: "assets/images/docs/mian_doc.jpg",
  color: myBlueColor),
  // Specialist(
  // id: 5,
  // title: "Bla Bla Bla",
  // price: 234,
  // ratings: 12,
  // speciality: 'Dentist',
  // image: "assets/images/docs/f_doc_2.jpg",
  // color: myBlueColor, ),
  ];

  static List<Specialist> Specialists=[Specialist(
      id: 1,
      title: "Dentist",
      price: 234,
      ratings: 12,
      speciality: dummyText,
      image: "assets/images/Teeth.svg",
      color: myBlueColor), Specialist(
      id: 2,
      title: "Cardiology",
      price: 234,
      ratings: 8,
      speciality: dummyText,
      image: "assets/images/heart.svg",
      color: myBlueColor), Specialist(
      id: 3,
      title: "Orthopae..",
      // title: "Orthopaedics",
      price: 234,
      ratings: 10,
      speciality: dummyText,
      image: "assets/images/joints.svg",
      color: myBlueColor), Specialist(
      id: 4,
      // title: "Gastroen",
      title: "Gastroen.",
      // title: "Neurology",
      price: 234,
      ratings: 11,
      speciality: dummyText,
      image: "assets/images/stomach.svg",
      color: myBlueColor),
    Specialist(
      id: 5,
      title: "Bla Bla Bla",
      price: 234,
      ratings: 12,
      speciality: dummyText,
      image: "assets/images/okb.svg",
      color: myBlueColor, ),
    // Specialist(
    //   id: 6,
    //   title: "Office Code",
    //   price: 234,
    //   ratings: 12,
    //   speciality: dummyText,
    //   image: "assets/images/bag_6.png",
    //   color: Color(0xFFAEAEAE),
    // ),Specialist(
    //     id: 1,
    //     title: "Office Code",
    //     price: 234,
    //     ratings: 12,
    //     speciality: dummyText,
    //     image: "assets/images/bag_1.png",
    //     color: myBlueColor), Specialist(
    //     id: 2,
    //     title: "Belt Bag",
    //     price: 234,
    //     ratings: 8,
    //     speciality: dummyText,
    //     image: "assets/images/bag_2.png",
    //     color: myBlueColor), Specialist(
    //     id: 3,
    //     title: "Hang Top",
    //     price: 234,
    //     ratings: 10,
    //     speciality: dummyText,
    //     image: "assets/images/bag_3.png",
    //     color: Color(0xFF989493)), Specialist(
    //     id: 4,
    //     title: "Old Fashion",
    //     price: 234,
    //     ratings: 11,
    //     speciality: dummyText,
    //     image: "assets/images/bag_4.png",
    //     color: Color(0xFFE6B398)),
    // Specialist(
    //   id: 5,
    //   title: "Office Code",
    //   price: 234,
    //   ratings: 12,
    //   speciality: dummyText,
    //   image: "assets/images/bag_5.png",
    //   color: Color(0xFFFB7883), ), Specialist(
    //   id: 6,
    //   title: "Office Code",
    //   price: 234,
    //   ratings: 12,
    //   speciality: dummyText,
    //   image: "assets/images/bag_6.png",
    //   color: Color(0xFFAEAEAE),
    // ),
  ];
}
String dummyText="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";